spring:  
    # kafka property에 대한 설명 >> https://oingdaddy.tistory.com/307
    kafka:    
        consumer:      
            bootstrap-servers: kafka01:9092,kafka02:9092,kafka03:9092      
            group-id: group-id-oing      
            auto-offset-reset: earliest      
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer      
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer    
        producer:      
            bootstrap-servers: kafka01:9092,kafka02:9092,kafka03:9092     
            key-serializer: org.apache.kafka.common.serialization.StringSerializer      
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
