spring:  
    # kafka property에 대한 설명 >> https://oingdaddy.tistory.com/307
    kafka:    
        consumer:      
            bootstrap-servers: 192.168.123.112:9092,192.168.123.125:9092,192.168.123.173:9092      
            group-id: group-id-oing      
            auto-offset-reset: earliest      
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer      
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer    
        producer:      
            bootstrap-servers: 192.168.123.112:9092,192.168.123.125:9092,192.168.123.173:9092     
            key-serializer: org.apache.kafka.common.serialization.StringSerializer      
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
